Cyrillux20240530
NatLibFi/marc-record-validators-melinda pull request #282
Opened 2024-06-06 10:51 UTC by nvolk

- New Cyrillux validator (move this functionality away from UI)

- also tune old usemarcon-cyrillux related rules

2024-06-06 11:37 UTC, natlibfi-jonollil requested changes

2024-06-06 11:37 UTC, natlibfi-jonollil commented on src/cyrillux.js
> +  function convertFieldToSfs4900Field880(field, occurrenceNumber) {
Could it work like this?
```js
function convertFieldToSfs4900Field880(field, occurrenceNumber) {
  // Looks like there's no need to fix composition, but I haven't tested extensively/checked
  return {
    tag: '880',
    ind1: field.ind1,
    ind2: field.ind2,
    subfields: [
      {code: '6', value: `${field.tag}-${occurrenceNumber}`},
      ...field.subfields.map(sf => convertSubfieldToSfs4900(sf)),
      {code: '9', value: 'SFS4900 <TRANS>'}
    ]
  };
}
```

2024-06-06 11:37 UTC, natlibfi-jonollil commented on src/cyrillux.js
> +      res.message.push(`TODO: ${orig} => ${mod}`); // eslint-disable-line functional/immutable-data
todo?

2024-06-06 11:47 UTC, nvolk commented on src/cyrillux.js
> +      res.message.push(`TODO: ${orig} => ${mod}`); // eslint-disable-line functional/immutable-data
Joo, TODO on huono. Toi siis kertoo tehtävän muutokset. Vaihdan tohon termin...

2024-06-07 06:04 UTC, nvolk commented on src/cyrillux.js
> +  function convertFieldToSfs4900Field880(field, occurrenceNumber) {
Yes.

2024-06-07 07:42 UTC, merged